<a href="https://colab.research.google.com/github/Deskola/Commercial-Api/blob/master/Tensor_Flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!pip install tensorflow --upgrade


Tensor flow test

In [0]:
import tensorflow as tf

In [0]:
A = tf.constant([1,2,3])

In [4]:
A


<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [0]:
B = tf.constant([10,10,10])

In [10]:
print(B)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [0]:
C= A+B


In [13]:
tf.print(C)#Vectorizatiion

[11 12 13]


In [14]:
D = A * B
tf.print(D)

[10 20 30]


MODEL

Importing data

In [17]:
from google.colab import files
upload = files.upload()

Saving Advertising.csv to Advertising.csv


In [0]:
import pandas as pd


In [0]:
data = pd.read_csv("Advertising.csv",index_col=0)

In [23]:
data.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [25]:
data.shape #structure of  data

(200, 4)

Splitting data into training and testing set

In [0]:
X = data[["TV","Radio","Newspaper"]].values #value convert type from dataframe to array

In [32]:
type(X)

numpy.ndarray

In [34]:
X.shape

(200, 3)

In [0]:
y = data[["Sales"]].values

In [40]:
#type(y)
y.shape

(200, 1)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3, random_state=42)

Training the model from our spli values

In [0]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(4,activation="sigmoid"),
    tf.keras.layers.Dense(1)
])

In [0]:
model.compile(optimizer="sgd",loss="mean_squared_error",metrics=["mean_squared_error"])

In [45]:
model.fit(X_train,y_train,epochs=500)

Train on 140 samples
Epoch 1/500
140/140 [==============================] - 0s 3ms/sample - loss: 212.5121 - mean_squared_error: 212.5121
Epoch 2/500
140/140 [==============================] - 0s 93us/sample - loss: 152.5478 - mean_squared_error: 152.5478
Epoch 3/500
140/140 [==============================] - 0s 81us/sample - loss: 111.5753 - mean_squared_error: 111.5753
Epoch 4/500
140/140 [==============================] - 0s 82us/sample - loss: 82.8925 - mean_squared_error: 82.8925
Epoch 5/500
140/140 [==============================] - 0s 76us/sample - loss: 62.7260 - mean_squared_error: 62.7260
Epoch 6/500
140/140 [==============================] - 0s 78us/sample - loss: 49.5112 - mean_squared_error: 49.5112
Epoch 7/500
140/140 [==============================] - 0s 97us/sample - loss: 40.5091 - mean_squared_error: 40.5091
Epoch 8/500
140/140 [==============================] - 0s 66us/sample - loss: 33.7860 - mean_squared_error: 33.7860
Epoch 9/500
140/140 [=========================

In [0]:
prediction = model.predict(X_test)

In [47]:
prediction

array([[15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [ 7.633299 ],
       [15.493757 ],
       [15.493112 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [ 7.633299 ],
       [15.493757 ],
       [15.493757 ],
       [ 7.633299 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [ 7.633299 ],
       [15.369142 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [ 7.633299 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [ 7.633299 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.49375  ],
       [15.493757 ],
       [15.493757 ],
       [ 7.6334834],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.493757 ],
       [15.49

In [48]:
for predicted,actual in zip(prediction, y_test):
  print("A",actual,"Pr", predicted)

A [16.9] Pr [15.493757]
A [22.4] Pr [15.493757]
A [21.4] Pr [15.493757]
A [7.3] Pr [7.633299]
A [24.7] Pr [15.493757]
A [12.6] Pr [15.493112]
A [22.3] Pr [15.493757]
A [8.4] Pr [15.493757]
A [11.5] Pr [15.493757]
A [14.9] Pr [15.493757]
A [9.5] Pr [15.493757]
A [8.7] Pr [15.493757]
A [11.9] Pr [15.493757]
A [5.3] Pr [7.633299]
A [10.3] Pr [15.493757]
A [11.7] Pr [15.493757]
A [5.5] Pr [7.633299]
A [16.6] Pr [15.493757]
A [11.3] Pr [15.493757]
A [18.9] Pr [15.493757]
A [19.7] Pr [15.493757]
A [12.5] Pr [7.633299]
A [10.9] Pr [15.369142]
A [22.2] Pr [15.493757]
A [9.3] Pr [15.493757]
A [8.1] Pr [15.493757]
A [21.7] Pr [15.493757]
A [13.4] Pr [15.493757]
A [10.6] Pr [15.493757]
A [5.7] Pr [7.633299]
A [10.6] Pr [15.493757]
A [11.3] Pr [15.493757]
A [23.7] Pr [15.493757]
A [8.7] Pr [7.633299]
A [16.1] Pr [15.493757]
A [20.7] Pr [15.493757]
A [11.6] Pr [15.493757]
A [20.8] Pr [15.493757]
A [11.9] Pr [15.493757]
A [6.9] Pr [15.49375]
A [11.] Pr [15.493757]
A [12.8] Pr [15.493757]
A [10.1] Pr

In [0]:
from sklearn.metrics import mean_squared_error

In [50]:
mean_squared_error(y_test,prediction)

23.68165319017866

In [52]:
mean_squared_error(y_train,model.predict(X_train))

18.559715062588943